### ISSUE TITLE
How to install the module

### ISSUE THREAD

**Issue by ansarul121** [AmpersandHQ/magento2-disable-stock-reservation#12]
Hi 

Can you please help me how to install the module ?

**Comment by convenient** [comment]
Hello

This module is hosted on packagist https://packagist.org/packages/ampersand/magento2-disable-stock-reservation

Run `composer require ampersand/magento2-disable-stock-reservation` to bring down the module

Then `php bin/magento setup:upgrade` to install it.

You'll need to commit and deploy it etc

**Comment by ansarul121** [comment]
HI @convenient 

Thanks for guiding me after installed the module backend product not loading you can have a look: https://prnt.sc/rn43ua

Can you please help me

**Comment by convenient** [comment]
@ansarul121 It should not have had any effect on the admin panel grids. It's likely something needs cleared and  regenerated after running `setup:upgrade` . See https://devdocs.magento.com/guides/v2.3/howdoi/php/php_clear-dirs.html#howdoi-clear-what

Alternatively re-run the steps you did to set up the project but keeping this dependency in place.

**Comment by ansarul121** [comment]
Hi @convenient 
Thanks for your help I have successfully installed the module but unfortunately something issue in the modules I have tested two product orders. it is correctly working you can have a look below 

order 1
Inventory details: https://prnt.sc/rnd3wy
order reference above snapshot: https://prnt.sc/rnd4oz
order 2
Inventory: https://prnt.sc/rnd6p6
Order reference above the inventory: https://prnt.sc/rnd7hl

Can you please help is how can I resolve the issue?

Thanks !

**Comment by convenient** [comment]
Hello @ansarul121 

It is difficult for me to assist as I don't know the particulars of your instance. Do you have existing reservations still in your `inventory_reservation` table that may be affecting this? This module should fix things going forward but perhaps if you have existing reservations it could be confused.

I can see that you have invoiced and shipped these orders, it would be difficult for me to understand the ordering of events.

What you could do is clone this repo and 
1. [Run the test suite against your instance](https://github.com/AmpersandHQ/magento2-disable-stock-reservation/blob/master/dev/codeception.MD), if it fails there is some customisation conflict that you will have on your side.
2. Add a test in a PR to this module to capture the issue as you see it.

Thanks,
Luke

**Comment by convenient** [comment]
Hello @ansarul121 

Your issue with the admin panel product grid not showing expected values sounds similar to what was discussed in #13 . In that issue the problem was that the indexers were not configured to be the same mode, or were not running. 

See https://github.com/AmpersandHQ/magento2-disable-stock-reservation#additional-notes

Maybe you can put both the indexers to `Update on save` mode locally to test it out?

**Comment by TheFrakes** [comment]
> 
> 
> Hello
> 
> This module is hosted on packagist https://packagist.org/packages/ampersand/magento2-disable-stock-reservation
> 
> Run `composer require ampersand/magento2-disable-stock-reservation` to bring down the module
> 
> Then `php bin/magento setup:upgrade` to install it.
> 
> You'll need to commit and deploy it etc

You should add this to the readme file. Like a section for "installation". Also, I am missing a "configuration" part. For example, I am unsure whether there is a new setting/menu in the admin area.
