### ISSUE TITLE
Exception while canceling old orders: Source model with the order ID "%1" does not exist

### ISSUE THREAD

**Issue by raulsinapsis** [AmpersandHQ/magento2-disable-stock-reservation#125]
I understand this happens since database table **order_sources** was added
If you try canceling old orders, which has no data in that database table then exception is thrown

To fix this, I understand this code should return default source model instead of throwing that exception

```
    public function getByOrderId(string $orderId): SourcesInterface
    {
        /** @var SourcesModel $sourcesModel */
        $sourcesModel = $this->sourcesFactory->create();

        $this->sourcesResourceModel->load(
            $sourcesModel,
            $orderId,
            SourcesInterface::ORDER_ID_KEY
        );

        if (!$sourcesModel->getId()) {
            throw new NoSuchEntityException(__('Source model with the order ID "%1" does not exist', $orderId));
        }

        return $sourcesModel;
    }
```

**Comment by convenient** [comment]
Recently worked on in https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/124

I think rather than modifying any sources the approach for old orders would be to do no stock modification, rather than returning stock to somewhere inappropriate?
