### ISSUE TITLE
sales_order_item_cancel should not be executed if "Set Items' Status to be In Stock When Order is Cancelled" is set to "No"

### ISSUE THREAD

**Issue by raulsinapsis** [AmpersandHQ/magento2-disable-stock-reservation#126]
Even if you set "Set Items' Status to be In Stock When Order is Cancelled" configuration to "No" the code in **Ampersand\DisableStockReservation\Observer\CancelOrderItemObserver** class is executed

Fix would be adding a configuration check in that observer

**Comment by convenient** [comment]
Makes sense. Any PRs would be happily welcomed
