### ISSUE TITLE
Php version

### ISSUE THREAD

**Issue by volodymyrdecima** [AmpersandHQ/magento2-disable-stock-reservation#136]
I see a requirement for php version 8.0
But new magento versions can use 8.1 and 8.2 already

**Comment by tr33m4n** [comment]
Hi @volodymyrdecima,

The semantic version `^8.0` covers all versions of PHP 8, up to <9.0 https://jubianchi.github.io/semver-check/#/^8.0/8.2

Are you seeing issues trying to install the module on a different PHP version?

Thanks

**Comment by volodymyrdecima** [comment]
Yep. 
Sorry. 
My fault.
