### ISSUE TITLE
Quantity not reduced for Stock Management = false

### ISSUE THREAD

**Issue by amenk** [AmpersandHQ/magento2-disable-stock-reservation#15]
The quantity does not seem to be reduced for products with stock management = false.

I believe this happend in older Magento versions where this module was not necessary.

My question is, whether it is in scope of this module to fix this and revert back to the old quantity behaviour.

**Comment by convenient** [comment]
@amenk Are you referring to the stetting "Manage Stock = No" at the product level under "Advanced Inventory"? 

I just did this locally
- On magento 2.2.11
- Simple product with 100 qty and `Manage Stock = No`
- check out with checkmo
- in admin panel I invoiced
- in admin panel I shipped
- I see that the product still has qty = 100 in admin and in database.

**Comment by amenk** [comment]
yes that is what I meant - thank you for testing, I feel too lazy now .)
