### ISSUE TITLE
Would this work with latest M2? 2.3.5

### ISSUE THREAD

**Issue by seansan** [AmpersandHQ/magento2-disable-stock-reservation#21]
Would this work with latest M2? 2.3.5

Readme mentions 2.3.3

**Comment by convenient** [comment]
The test suite is currently green for 2.3.5-p1, see the output from `magerun2 sys:info` in the build

https://travis-ci.org/github/AmpersandHQ/magento2-disable-stock-reservation/jobs/693556611

The suite runs against a known working version (2.3.3) and the latest magento version.
