### ISSUE TITLE
Issue while Posting Shipment via API

### ISSUE THREAD

**Issue by sukhy** [AmpersandHQ/magento2-disable-stock-reservation#29]
I have installed the extension in my Magento Installation and working fine.

But whenever i trigger a Shipment via API it give me error, here is the screenshot https://prnt.sc/t6xtfe

It was working fine before installation of the extension.

**Comment by convenient** [comment]
Hello

We use the shipment API on our clients without issue. Furthermore shipment via the API is covered in this test https://github.com/AmpersandHQ/magento2-disable-stock-reservation/blob/d5751b1a3428a53ae5382151ba45e80ca9214798/dev/tests/acceptance/CheckoutCest.php#L86

I recommend you try and replicate this locally and debug, perhaps its conflicting with some customisation

**Comment by convenient** [comment]
Closing this as we continue to use shipments via rest api without issue https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/110

This can be reopened if verified thanks
