### ISSUE TITLE
Unable to place an order for group products

### ISSUE THREAD

**Issue by anuradha** [AmpersandHQ/magento2-disable-stock-reservation#36]
In **ampersand/magento2-disable-stock-reservation/src/Model/GetInventoryRequestFromOrder.php:87** uses the **Magento\InventorySourceSelectionApi\Api\Data\InventoryRequestInterface** and returns the **StockId** and **Items**.

`$inventoryRequest = $this->inventoryRequestFactory->create([`
`'stockId' => $stock->getStockId(),`
`'items'   => $requestItems`
`]);`

But this **requestItems** returns **null**.

Found the issue in **ampersand/magento2-disable-stock-reservation/src/Model/GetSourceSelectionResultFromOrder.php#103**

`foreach ($orderItems as $orderItem) {`
`if (!$this->isSourceItemManagementAllowedForProductType->execute($orderItem->getProductType())) {`
` continue;`
` }`

When **$orderItem->getProductType()** is **grouped**,

` if (!$this->isSourceItemManagementAllowedForProductType->execute($orderItem->getProductType())) {` **return false** and unable to continue the checkout process. Getting the below error.

> PHP Fatal error: Uncaught TypeError: Return value of Magento\InventorySourceSelection\Model\Request\InventoryRequest::getItems() must be of the type array, null returned in /www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php:102
Stack trace:
#0 /www/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php(97): Magento\InventorySourceSelection\Model\Request\InventoryRequest->getItems()
magento/magento2#1 /www/vendor/magento/module-inventory-source-selection/Model/Algorithms/PriorityBasedAlgorithm.php(73): Magento\InventorySourceSelectionApi\Model\Algorithms\Result\GetDefaultSortedSourcesResult->execute(Object(Magento\InventorySourceSelection\Model\Request\InventoryRequest), Array)
magento/magento2#2 /www/vendor/magento/module-inventory-source-selection-api/Model/SourceSelectionService.php(61) in /www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php on line 102

Is there a fix for this? if not can you please check this issue?
Appreciate an immediate response.

**Comment by kestraly** [comment]
I just found this issue as well. Error we received was:

PHP message: PHP Fatal error:  Uncaught TypeError: Return value of Magento\\InventorySourceSelection\\Model\\Request\\InventoryRequest::getItems() must be of the type array, null returned in vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php:102

Howeve I applied the patch for Bundle Products MDVA-30889 and it resolved the issue

https://support.magento.com/hc/en-us/articles/360052403931-MDVA-30889-Magento-patch-Cannot-invoice-orders-which-contain-bundle-products-with-virtual-and-simple-products-as-options

I still have the following error though
Reference to undeclared plugin with name 'priceIndexUpdater' - So disabled this from vendor/magento/module-inventory-catalog/etc/di.xml

**Comment by adrian-martinez-interactiv4** [comment]
> Hello thanks for this issue.
> 
> We have no fix for this issue currently.
> 
> ```
> $this->isSourceItemManagementAllowedForProductType->execute($orderItem->getProductType())
> ```
> 
> To fix this I would
> 
> 1. Look at how source item management is usually achieved for group products
> 2. Try to implement similar checking here

Tried to fix it at https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/46.

**Comment by liamjtoohey** [comment]
Closing as this is now resolved in https://github.com/AmpersandHQ/magento2-disable-stock-reservation/releases/tag/1.0.16

Thanks again for your contributions! @adrian-martinez-interactiv4 @anuradha @kestraly
