### ISSUE TITLE
Stock replenishment on multi source inventories

### ISSUE THREAD

**Issue by qrz-io** [AmpersandHQ/magento2-disable-stock-reservation#4]
Vanilla MSI with stock reservations only does source selection on shipments, and inventory sources are saved against each shipment.

Because this module forces source selection on order placement, and there's no other place to store said selections, we have no way to tell where to replenish stock in case of cancellations or credit memos.

Implementation was started for cancellation in the `CancelOrderItemObserver` but this only works for single source inventories at the moment.

**Comment by moiashvin** [comment]
Hi, I am also having this issue for the multi-source inventories but code not written for this flow. 
I see comment says:        // @TODO add support for multi source stock replenishment on cancellation
Is there a work-around in meanwhile?

**Comment by convenient** [comment]
@moiashvin I think this PR was going to be an attempt at handling this https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/6

However the module has been through a bit of a refactor since then and we never pursued it further as we did not end up needing it.

**Comment by moiashvin** [comment]
Hi @convenient  thanks for your message. Does this mean that without that code, the qty will not be restored correctly if there are more than one source stock? Is there a way to have it work?

In my case, I have more than 1 source (i.e. default for online shop, and others for physical boutiques) but have only 1 stock (default) defined and linked to the site. However, because there are more than 1 source, it never restore the qty on cancellation of order.

**Comment by convenient** [comment]
@moiashvin Thats my understanding yes. I think we were planning on trying to track the source so that we could know how to properly restore it when there are multiple sources.  

We never completed the work I'm afraid, but you could use this PR as inspiration? Sorry, it would be custom development.

**Comment by davidwindell** [comment]
Is this resolved now with the merge of !6?

**Comment by tr33m4n** [comment]
@convenient @qrz-io Did this get resolved does anyone know?

**Comment by qrz-io** [comment]
@tr33m4n it does get resolved with #6, this issue should be closed.

**Comment by tr33m4n** [comment]
Resolved by https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/6
