### ISSUE TITLE
Negative out of stock threshold

### ISSUE THREAD

**Issue by jeroencusters** [AmpersandHQ/magento2-disable-stock-reservation#47]
Hi, we use Magento 2.4.2 with external WMS system and have disabled Magento MSI (requirement external WMS system). Since MSI is disabled we can't use negative out of stock threshold (https://docs.magento.com/user-guide/catalog/inventory-backorders.html) and we need this for some pre-order / backorder products. Is it possible to use negative out of stock threshold when we re-enable MSI and install this plugin? Thanks in advance for your help!

**Comment by convenient** [comment]
Hi @jeroencusters 

We have not tested it with this functionality I think. You will need to try it and let us know how it goes. 

Thanks

**Comment by tr33m4n** [comment]
Hi @jeroencusters, did you manage to resolve your issue? Thanks

**Comment by jeroencusters** [comment]
Hi @tr33m4n, we don't use this plugin. We created a workaround with extra product fields and Magento API.

**Comment by bricht** [comment]
:( backorders dont quite work because negative qty seems to not be possible. When you do a backorder which should reduce product qty below 0, it just stays at 0. Then if you cancel or creditmemo that order - the product stock goes up.
