### ISSUE TITLE
Uncaught Error: Cannot instantiate interface

### ISSUE THREAD

**Issue by bao-concise** [AmpersandHQ/magento2-disable-stock-reservation#52]
Place Order

### Preconditions (*)
1. Magento 2.4.2
2.  PHP 7.4

### Steps to reproduce (*)
1. Order a product
2. Checkout 
3. Place Order

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)
1. Order Success
2. Does not redirect to success page
3. Does not send email after place order

---
### Errors: 

`main.CRITICAL: Error: Cannot instantiate interface Magento\InventorySourceSelectionApi\Api\GetDefaultSourceSelectionAlgorithmCodeInterface in /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...')
#1 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Invento...')
#2 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Invento...', NULL, 'getDefaultSourc...', 'Ampersand\\Disab...')
#3 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Ampersand\\Disab...', Array, Array)
#4 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Ampersand\\Disab...', Array, Array)
#5 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Ampersand\\Disab...', Array, Array)
#6 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Ampersand\\Disab...')
#7 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Ampersand\\Disab...')
#8 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Ampersand\\Disab...', NULL, 'getSourceSelect...', 'Ampersand\\Disab...')
#9 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Ampersand\\Disab...', Array, Array)
#10 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Ampersand\\Disab...', Array, Array)
#11 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Ampersand\\Disab...', Array, Array)
#12 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Ampersand\\Disab...')
#13 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/PluginList/PluginList.php(174): Magento\Framework\ObjectManager\ObjectManager->get('Ampersand\\Disab...')
#14 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(144): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Sales\\M...', 'inventory_sales...')
#15 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(195): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#16 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
#17 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#18 /var/www/html/web/releases/20210729092246/public/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(32): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, Array)
#19 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-quote/Model/QuoteManagement.php(566): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
#20 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#21 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#22 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', Array)
#23 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
#24 /var/www/html/web/releases/20210729092246/public/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(23): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', Array, Array)
#25 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-quote/Model/QuoteManagement.php(414): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#26 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(120): Magento\Quote\Model\QuoteManagement->placeOrder(5705)
#27 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(5705, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#28 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#29 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(5705, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#30 /var/www/html/web/releases/20210729092246/public/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#31 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(5705, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#32 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#33 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#34 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#36 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /var/www/html/web/releases/20210729092246/public/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#38 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /var/www/html/web/releases/20210729092246/public/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#40 /var/www/html/web/releases/20210729092246/public/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#41 {main} [] []`

**Comment by convenient** [comment]
Hello @bao-concise 

## Test coverage does not reproduce the issue

In our tests we place an order as guest via the API

https://github.com/AmpersandHQ/magento2-disable-stock-reservation/blob/5a52af0fb3acc5078a597549dadaa8049b5aece8/dev/tests/_support/Step/Acceptance/Magento.php#L159-L165

looking at the trace provided you do similar here

```
#31 Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(5705, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor)) 
#32 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array) 
#33 /var/www/html/web/releases/20210729092246/public/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor-
```

Our last test run was this one https://travis-ci.org/github/AmpersandHQ/magento2-disable-stock-reservation/jobs/774514076 which had the following setup (as an aside i have raised https://github.com/AmpersandHQ/magento2-disable-stock-reservation/issues/53 as travis builds are not working currently)
```
+------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| name             | value                                                                                                                               |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Name             | Magento                                                                                                                             |
| Version          | 2.4.2-p1                                                                                                                            |
| Edition          | Community                                                                                                                           |
| Application Mode | default                                                                                                                             |
| Session          | files                                                                                                                               |
```

Our current tests do not exhibit this error, but possibly some configuration is required to trigger it.

## Debugging steps

Can you please run the following and provide output?

```
composer info magento/module-inventory-source-selection-api
```

```
composer why magento/module-inventory-source-selection-api
```

**Comment by bao-concise** [comment]
These are steps as your guide. Thanks
> ```
> composer info magento/module-inventory-source-selection-api
> ```

```
[centos@local public]$ composer info magento/module-inventory-source-selection-api
name     : magento/module-inventory-source-selection-api
descrip. : N/A
keywords :
versions : * 1.4.0
type     : magento2-module
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
license  : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/licenses/AFL-3.0.html#licenseText
homepage :
source   : []
dist     : [zip] https://repo.magento.com/archives/magento/module-inventory-source-selection-api/magento-module-inventory-source-selection-api-1.4.0.0.zip
path     : /var/www/html/web/releases/20210729123200/public/vendor/magento/module-inventory-source-selection-api
names    : magento/module-inventory-source-selection-api

autoload
files
psr-4
Magento\InventorySourceSelectionApi\ => .

requires
magento/framework *
magento/module-inventory-api 1.2.*
magento/module-inventory-sales-api 1.2.*
magento/module-sales *
magento/module-store *
php ~7.3.0||~7.4.0
You have mail in /var/spool/mail/centos
```
```
composer why magento/module-inventory-source-selection-api
magento/inventory-metapackage                                 1.2.2  requires  magento/module-inventory-source-selection-api (1.4.0)
magento/module-inventory-distance-based-source-selection      1.2.0  requires  magento/module-inventory-source-selection-api (1.4.*)
magento/module-inventory-distance-based-source-selection-api  1.2.0  requires  magento/module-inventory-source-selection-api (1.4.*)
magento/module-inventory-in-store-pickup                      1.1.0  requires  magento/module-inventory-source-selection-api (1.4.*)
magento/module-inventory-in-store-pickup-sales                1.1.0  requires  magento/module-inventory-source-selection-api (1.4.*)
magento/module-inventory-sales                                1.2.0  requires  magento/module-inventory-source-selection-api (1.4.*)
magento/module-inventory-shipping                             1.2.0  requires  magento/module-inventory-source-selection-api (1.4.*)
magento/module-inventory-shipping-admin-ui                    1.2.0  requires  magento/module-inventory-source-selection-api (1.4.*)
magento/module-inventory-source-selection                     1.2.0  requires  magento/module-inventory-source-selection-api (1.4.*)
You have mail in /var/spool/mail/centos

```

**Comment by convenient** [comment]
@bao-concise Same versions as one of my instances.

Can you confirm the file exists at the following location?
```
/var/www/html/web/releases/20210729123200/public/vendor/magento/module-inventory-source-selection-api/vendor/magento/module-inventory-source-selection-api/Api/GetDefaultSourceSelectionAlgorithmCodeInterface.php
```

Is it possible you have disabled/replaced some of the core modules to cause this issue? I see a similar trace in this issue https://github.com/magento/magento2/pull/23264

**Comment by bao-concise** [comment]
@convenient Thank you for your response,

Yes, that file exists as given location, this is log

```
[centos@local public]$ test -f vendor/magento/module-inventory-source-selection-api/Api/GetDefaultSourceSelectionAlgorithmCodeInterface.php && echo "$FILE exists."
 exists.
You have mail in /var/spool/mail/centos
[centos@local public]$ cat vendor/magento/module-inventory-source-selection-api/Api/GetDefaultSourceSelectionAlgorithmCodeInterface.php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\InventorySourceSelectionApi\Api;

/**
 * Service returns Default Source Selection Algorithm Code
 *
 * @api
 */
interface GetDefaultSourceSelectionAlgorithmCodeInterface
{
    /**
     * Get Default Algorithm code
     *
     * @return string
     */
    public function execute(): string;
}
```

> Is it possible you have disabled/replaced some of the core modules to cause this issue?

I didn't do anything with the core, my Magento is upgraded from 2.1 to 2.4, But the issue just happened when I install this module

**Comment by convenient** [comment]
@bao-concise  are you able to share the results of `php bin/magento module:status` ?

**Comment by bao-concise** [comment]
@convenient sure, this is the result, hope you can help me. Thanks
```
[centos@local public]$ php bin/magento module:status
List of enabled modules:
Magento_AdminAnalytics
Magento_Store
Magento_AdobeIms
Magento_AdobeImsApi
Magento_AdobeStockAdminUi
Magento_MediaGallery
Magento_AdobeStockAssetApi
Magento_AdobeStockClient
Magento_AdobeStockClientApi
Magento_AdobeStockImage
Magento_Directory
Magento_AdobeStockImageApi
Magento_AdvancedPricingImportExport
Magento_Theme
Magento_Amqp
Magento_AmqpStore
Magento_Config
Magento_Backend
Magento_Authorization
Magento_Eav
Magento_Search
Magento_Backup
Magento_Variable
Magento_Customer
Magento_BundleImportExport
Magento_CacheInvalidate
Magento_AdminNotification
Magento_Indexer
Magento_Cms
Magento_Security
Magento_GraphQl
Magento_EavGraphQl
Magento_StoreGraphQl
Magento_CatalogImportExport
Magento_Catalog
Magento_CatalogInventory
Magento_Rule
Magento_Payment
Magento_CatalogRuleGraphQl
Magento_CatalogRule
Magento_CatalogUrlRewrite
Magento_CatalogGraphQl
Magento_Widget
Magento_Quote
Magento_SalesSequence
Magento_CheckoutAgreementsGraphQl
Magento_MediaGalleryUi
Magento_CmsGraphQl
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
Magento_CompareListGraphQl
Magento_ComposerRootUpdatePlugin
Magento_User
Magento_Msrp
Magento_Sales
Magento_QuoteGraphQl
Magento_Checkout
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_Csp
Magento_CurrencySymbol
Magento_Bundle
Magento_Integration
Magento_Downloadable
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_CatalogCustomerGraphQl
Magento_DirectoryGraphQl
Magento_DownloadableGraphQl
Magento_CustomerDownloadableGraphQl
Magento_ImportExport
Magento_Captcha
Magento_BundleGraphQl
Magento_CatalogSearch
Magento_AdvancedSearch
Magento_Elasticsearch
Magento_Email
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_GiftMessageGraphQl
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_Ui
Magento_GoogleShoppingAds
Magento_CatalogCmsGraphQl
Magento_PageCache
Magento_GroupedProduct
Magento_GroupedImportExport
Magento_GroupedCatalogInventory
Magento_GroupedProductGraphQl
Magento_DownloadableImportExport
Magento_ConfigurableProduct
Magento_InstantPurchase
Magento_Analytics
Magento_Inventory
Magento_InventoryApi
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogApi
Magento_InventoryCatalogFrontendUi
Magento_InventoryCatalogSearch
Magento_InventoryConfigurableProductFrontendUi
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryElasticsearch
Magento_InventoryIndexer
Magento_InventorySalesApi
Magento_Shipping
Magento_Multishipping
Magento_Webapi
Magento_Reports
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
Magento_CatalogInventoryGraphQl
Magento_InventorySourceDeductionApi
Magento_InventorySwatchesFrontendUi
Magento_InventoryWishlist
Magento_LayeredNavigation
Magento_LoginAsCustomer
Magento_LoginAsCustomerAdminUi
Magento_LoginAsCustomerApi
Magento_LoginAsCustomerFrontendUi
Magento_LoginAsCustomerGraphQl
Magento_LoginAsCustomerLog
Magento_LoginAsCustomerPageCache
Magento_LoginAsCustomerQuote
Magento_LoginAsCustomerSales
Magento_Marketplace
Magento_MediaContent
Magento_MediaContentApi
Magento_MediaContentCatalog
Magento_MediaContentCms
Magento_MediaContentSynchronization
Magento_MediaContentSynchronizationApi
Magento_MediaContentSynchronizationCatalog
Magento_MediaContentSynchronizationCms
Magento_AdobeStockAsset
Magento_MediaGalleryApi
Magento_MediaGalleryCatalog
Magento_MediaGalleryCatalogIntegration
Magento_MediaGalleryCatalogUi
Magento_MediaGalleryCmsUi
Magento_MediaGalleryIntegration
Magento_MediaGalleryMetadata
Magento_MediaGalleryMetadataApi
Magento_MediaGalleryRenditions
Magento_MediaGalleryRenditionsApi
Magento_MediaGallerySynchronization
Magento_MediaGallerySynchronizationApi
Magento_MediaGallerySynchronizationMetadata
Magento_AdobeStockImageAdminUi
Magento_MediaGalleryUiApi
Magento_Robots
Magento_MessageQueue
Magento_CatalogRuleConfigurable
Magento_MsrpConfigurableProduct
Magento_MsrpGroupedProduct
Magento_MysqlMq
Magento_NewRelicReporting
Magento_Newsletter
Magento_NewsletterGraphQl
Magento_OfflinePayments
Magento_SalesRule
Magento_GraphQlCache
Magento_CardinalCommerce
Magento_Vault
Magento_Paypal
Magento_PaypalGraphQl
Magento_Persistent
Magento_ProductAlert
Magento_ProductVideo
Magento_CheckoutAgreements
Magento_QuoteAnalytics
Magento_QuoteBundleOptions
Magento_QuoteConfigurableOptions
Magento_QuoteDownloadableLinks
Magento_ConfigurableProductGraphQl
Magento_ReCaptchaAdminUi
Magento_ReCaptchaCheckout
Magento_ReCaptchaContact
Magento_ReCaptchaCustomer
Magento_ReCaptchaFrontendUi
Magento_ReCaptchaMigration
Magento_ReCaptchaNewsletter
Magento_ReCaptchaPaypal
Magento_ReCaptchaReview
Magento_ReCaptchaSendFriend
Magento_ReCaptchaUi
Magento_ReCaptchaUser
Magento_ReCaptchaValidation
Magento_ReCaptchaValidationApi
Magento_ReCaptchaVersion2Checkbox
Magento_ReCaptchaVersion2Invisible
Magento_ReCaptchaVersion3Invisible
Magento_RelatedProductGraphQl
Magento_ReleaseNotification
Magento_Sitemap
Magento_RequireJs
Magento_Review
Magento_ReviewAnalytics
Magento_ReviewGraphQl
Magento_MediaStorage
Magento_Rss
Magento_Elasticsearch6
Magento_ConfigurableProductSales
Magento_SalesAnalytics
Magento_SalesGraphQl
Magento_SalesInventory
Magento_OfflineShipping
Magento_ConfigurableImportExport
Magento_UrlRewrite
Magento_Elasticsearch7
Magento_CustomerAnalytics
Magento_Securitytxt
Magento_SendFriend
Magento_SendFriendGraphQl
Magento_RemoteStorage
Magento_AwsS3
Magento_UrlRewriteGraphQl
Magento_Swagger
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_Tax
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_AsynchronousOperations
Magento_ThemeGraphQl
Magento_Tinymce3
Magento_Translation
Magento_GoogleOptimizer
Magento_Ups
Magento_SampleData
Magento_CatalogUrlRewriteGraphQl
Magento_CatalogAnalytics
Magento_Usps
Magento_PaypalCaptcha
Magento_VaultGraphQl
Magento_Version
Magento_WebapiAsync
Magento_WebapiSecurity
Magento_Weee
Magento_WeeeGraphQl
Magento_CatalogWidget
Magento_Wishlist
Magento_WishlistAnalytics
Magento_WishlistGraphQl
Amasty_Base
Amasty_Label
Amazon_Core
Amazon_Login
Amazon_Payment
Bss_CheckoutCustomField
Dotdigitalgroup_Email
Dotdigitalgroup_Chat
Dotdigitalgroup_Sms
Ebizmarts_MailChimp
FME_Restrictcustomergroup
Jh_SymlinkAssetDeploys
Klarna_Core
Klarna_Ordermanagement
Klarna_Kp
Klarna_Onsitemessaging
Klarna_KpGraphQl
Korimco_Attache
Korimco_Catalog
Korimco_CatalogInventory
Korimco_Checkout
Korimco_Customer
Korimco_CustomerDiscount
Korimco_Design
Korimco_Eta
Korimco_GroupedProduct
Korimco_Header
Korimco_HierarchyDiscount
Korimco_Korimcofreeshipping
Korimco_MinimumOrder
Korimco_NoDiscount
Korimco_OrderGridColoring
Korimco_Parcelnet
Korimco_UrlkeyRewrite
Korimco_Wishlist
MSP_Common
Mageplaza_Core
Mageplaza_CustomerApproval
Mageplaza_QuickOrder
Mageplaza_QuickView
Mageplaza_Smtp
Plazathemes_Bannerslider
Plazathemes_Bestsellerproduct
Plazathemes_Brandslider
Plazathemes_Categorytab
Plazathemes_Featureproductslider
Plazathemes_Hozmegamenu
Plazathemes_Layout
Plazathemes_Loadjs
Plazathemes_Newproductslider
Plazathemes_Newsletterpopup
Plazathemes_Override
Plazathemes_Pricecountdown
Plazathemes_Recentproductslider
Plazathemes_Template
Plazathemes_Themeoptions
Temando_ShippingRemover
Vertex_Tax
Vertex_AddressValidationApi
Vertex_AddressValidation
Webkul_CustomRegistration
Webkul_ShowPriceAfterLogin
Yotpo_Yotpo

List of disabled modules:
Magento_InventoryAdminUi
Magento_InventoryAdvancedCheckout
Magento_InventoryBundleImportExport
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryBundleProductIndexer
Magento_InventoryCatalogAdminUi
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryExportStockApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryInStorePickupApi
Magento_InventoryInStorePickupAdminUi
Magento_InventorySourceSelectionApi
Magento_InventoryInStorePickup
Magento_InventoryInStorePickupGraphQl
Magento_InventoryInStorePickupShippingApi
Magento_InventoryInStorePickupQuoteGraphQl
Magento_InventoryInStorePickupSales
Magento_InventoryInStorePickupSalesApi
Magento_InventoryInStorePickupQuote
Magento_InventoryInStorePickupShipping
Magento_InventoryInStorePickupShippingAdminUi
Magento_InventoryCache
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryProductAlert
Magento_InventoryRequisitionList
Magento_InventoryExportStock
Magento_InventorySalesAdminUi
Magento_InventorySalesFrontendUi
Magento_InventorySetupFixtureGenerator
Magento_InventoryShipping
Magento_InventoryShippingAdminUi
Magento_InventorySourceSelection
Magento_InventoryInStorePickupFrontend
Magento_InventoryVisualMerchandiser
Magento_LoginAsCustomerAssistance
Magento_InventoryInStorePickupMultishipping
Magento_InventoryLowQuantityNotificationAdminUi
Magento_InventoryInStorePickupSalesAdminUi
Magento_TwoFactorAuth
Magento_InventoryGraphQl
Magento_InventoryInStorePickupWebapiExtension
Ampersand_DisableStockReservation
KiwiCommerce_LoginAsCustomer
MSP_DevTools
PayPal_Braintree
PayPal_BraintreeGraphQl
```

**Comment by convenient** [comment]
You have disabled the `Magento_InventorySourceSelectionApi` module as well as `Magento_InventorySourceSelection`.

You need the inventory modules to be enabled for this module to work.

**Comment by bao-concise** [comment]
@convenient thank you very much for your kind support, It is work now

**Comment by convenient** [comment]
no problems 👍
