### ISSUE TITLE
Allow Shipment with 0 Qty

### ISSUE THREAD

**Issue by nthurston** [AmpersandHQ/magento2-disable-stock-reservation#69]
Do you guys have any plans to add a feature that would allow shipment even if source has 0 qty? -- To clarify, it's actually if the item is "Out Of Stock", it will allow you to ship at 0 qty if item is "In Stock" (e.g. allow backorders)

I thought maybe this module would help our case, but doesn't seem to do the above.

Issue presents when someone buys the last qty of some item.
1. Order Syncs to ERP
2. ERP commits the qty
3. ERP syncs inventory up and tells the website there is 0
4. Magento does not allow shipment to be made (from admin) - no sources appear in the dropdown of Select a Source to Ship from

We have some integrations that use admin to ship products, some that ship in the ERP.  Not sure yet if the second case is solved (i.e. if an API call to ship the order would work)

**Comment by zeeshan2523806** [comment]
@nthurston did you find any workaround for this ? we are experiencing the same issue but the only difference is if a customer purchases the last quantity and then the order gets canceled, the stock is added back to normal but the stock status is still set to Out of Stock for that item even though we have the stock quantity returned from the cancelled order.

**Comment by nthurston** [comment]
@zeeshan2523806 Yes we did.  I was going to submit a PR but we ended up with kind of a mixed bag of approaches between this module and a comment I found in another thread.  So I'm not sure if it's totally usable in the context of this module's approach.

In adminhtml/di.xml
```
    <!-- Show all assigned sources for all items during shipment creation (regardless of in/out of stock -->
    <preference
            for="Magento\InventorySourceSelectionApi\Model\GetInStockSourceItemsBySkusAndSortedSource"
            type="Vendor\Module\Model\InventoryApi\GetInStockSourceItemsBySkusAndSortedSource" />

    <!--  Pretend All Items are not Manage Stock for shipping purposes  -->
    <type name="Magento\InventoryShippingAdminUi\Ui\DataProvider\SourceSelectionDataProvider">
        <plugin name="disable_manage_stock_for_shipping" type="Vendor\Module\Plugin\InventoryShippingAdminUi\Ui\DataProvider\SourceSelectionDataProviderPlugin"/>
    </type>

    <!--  Allow sending pickup notif at 0 qty/out of stock  -->
    <type name="Magento\InventoryInStorePickupSales\Model\Order\IsFulfillable">
        <plugin name="allow_pickup_notif" type="Vendor\Module\Plugin\InventoryInStorePickupSales\Model\Order\IsFulfillablePlugin"/>
    </type>
```

Preference this class and comment out the "in stock" filter - this makes it so the dropdown shows all sources regardless of what is or isn't "in stock".

```
<?php

namespace Vendor\Module\Model\InventoryApi;

use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\InventoryApi\Api\Data\SourceItemInterface;
use Magento\InventoryApi\Api\SourceItemRepositoryInterface;

class GetInStockSourceItemsBySkusAndSortedSource
{
        /**
     * @var SourceItemRepositoryInterface
     */
    private $sourceItemRepository;

    /**
     * @var SearchCriteriaBuilder
     */
    private $searchCriteriaBuilder;

    /**
     * @param SourceItemRepositoryInterface $sourceItemRepository
     * @param SearchCriteriaBuilder $searchCriteriaBuilder
     * @SuppressWarnings(PHPMD.LongVariable)
     */
    public function __construct(
        SourceItemRepositoryInterface $sourceItemRepository,
        SearchCriteriaBuilder $searchCriteriaBuilder
    ) {
        $this->sourceItemRepository = $sourceItemRepository;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
    }

    /**
     * Retrieve source items for a defined set of SKUs and sorted source codes
     *
     * @param array $skus
     * @param array $sortedSourceCodes
     * @return SourceItemInterface[]
     */
    public function execute(array $skus, array $sortedSourceCodes): array
    {
        $skus = array_map('strval', $skus);
        $searchCriteria = $this->searchCriteriaBuilder
            ->addFilter(SourceItemInterface::SKU, $skus, 'in')
            ->addFilter(SourceItemInterface::SOURCE_CODE, $sortedSourceCodes, 'in')
            //->addFilter(SourceItemInterface::STATUS, SourceItemInterface::STATUS_IN_STOCK)
            ->create();

        $items = $this->sourceItemRepository->getList($searchCriteria)->getItems();

        $itemsSorting = [];
        foreach ($items as $item) {
            $itemsSorting[] = array_search($item->getSourceCode(), $sortedSourceCodes, true);
        }

        array_multisort($itemsSorting, SORT_NUMERIC, SORT_ASC, $items);
        return $items;
    }
}
```

Plugin that makes the UI think that everything is "not manage stock" otherwise you get frontend and backend validation that will prevent you from shipping something that is considered out of stock.

```
<?php

namespace Cpcommerce\SourceApi\Plugin\InventoryShippingAdminUi\Ui\DataProvider;

use Magento\InventoryShippingAdminUi\Ui\DataProvider\SourceSelectionDataProvider;

class SourceSelectionDataProviderPlugin
{
    public function afterGetData(SourceSelectionDataProvider $subject, $result)
    {
        foreach ($result as &$data) {
            foreach ($data['items'] as &$item) {
                $item['isManageStock'] = 0;
            }
        }

        return $result;
    }
}
```

Plugin that makes it so store pickup believes that items are fulfillable even if they're not.

```
<?php

namespace Cpcommerce\SourceApi\Plugin\InventoryInStorePickupSales\Model\Order;

class IsFulfillablePlugin
{
    public function aroundExecute()
    {
        return true;
    }
}
```

Though to be honest, in your case you might be better off trying to get it so that cancels just make the item in stock instead of all this workaround to let it ship an out of stock product.  In our case, the item is considered "out of stock" because our ERP has 0 available after committing the order.

**Comment by convenient** [comment]
Hello there are a few cases being discussed here. 

Firstly @zeeshan2523806 

> we are experiencing the same issue but the only difference is if a customer purchases the last quantity and then the order gets canceled, the stock is added back to normal but the stock status is still set to Out of Stock for that item even though we have the stock quantity returned from the cancelled order

The product restock status bug was fixed by @gianstraf and tagged in https://github.com/AmpersandHQ/magento2-disable-stock-reservation/releases/tag/1.2.2

Secondly the details from @nthurston

The `InventoryInStorePickupSales` seemed valid, and has been tagged here https://github.com/AmpersandHQ/magento2-disable-stock-reservation/releases/tag/1.2.4

That leaves outstanding the other approach, where you say that the shipments cannot be created when the product is at qty=0, can you confirm that this only happens via the UI as the rest api test I've spun up here seems like everything is working as expected ? https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/110 It would be good to verify the only outstanding case is "ship order and items at qty=0 via the admin UI" 

thanks

**Comment by convenient** [comment]
I have added more tests and also manually tested on 2.4.3

I was able to have the product at `qty=0` `is_in_stock=0` and ship the order with all the items 🤔 

In three ways 
- Integration test of adminhtml controller
- Manually via the admin panel
- Rest api

https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/110

I am not sure what else I am missing
