### ISSUE TITLE
Magento 2.4.4 and PHP 8.1 support

### ISSUE THREAD

**Issue by sweikas** [AmpersandHQ/magento2-disable-stock-reservation#71]
Do you guys have any plans making this module compatible with latest magento version?

**Comment by convenient** [comment]
Hello @sweikas 

We definitely will be making it compatible with 2.4.4 but I do not yet have the timelines on that I'm afraid. I'm making a few tweaks in a branch just to see what breaks in travis to get a sort of baseline

**Comment by convenient** [comment]
@sweikas https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/72

I have not been able to properly test it in a real magento instance, but the travis build has gone green. Would you be able to composer require this branch perhaps to test with your instance before I merge and tag?

**Comment by sweikas** [comment]
@convenient Thanks for a quick reply. I'll try to do that tomorrow and will let you know.

**Comment by sweikas** [comment]
@convenient it looks like the module is working without any issues. I haven't tested more intricate scenarios though (just some regular orders). Thanks a lot!

**Comment by convenient** [comment]
The main change was in the `composer.json` to allow PHP 8, so I've merged and tagged.

We've not extensively tested it, but my suite is going green so that's a good start.
