### ISSUE TITLE
No stock is added back when creating creditmemo without having shipped the item

### ISSUE THREAD

**Issue by norgeindian** [AmpersandHQ/magento2-disable-stock-reservation#8]
The refunded qty is not added back to stock if one creates a creditmemo for an order which has no shipment yet.
This kind of make sense, as Magento itself would have reserved the qty but not deducted it from the stock of the product. So there would be no need to add it again as long as no shipment exists.

**Comment by seansan** [comment]
HI, i was going to ask a question about returns processing and credit memo's (both invoiced, invoice+shipped) ... is credit memo processing and return to stock supported?

**Comment by philipp-greenique** [comment]
Hi there, we have the same problem, that the stock is not added back with a credit memo while not shipped.

**Comment by jyoti23kadam** [comment]
@norgeindian 
i have the same problem .Please tell us the proper solution.

**Comment by convenient** [comment]
There is currently no solution for this. The functionality would need to be built into this module.

This issue has not been a problem for our clients on it so we are not actively allocating developers to tackle this issue, we would be happy to engage with any pull requests that are raised.

**Comment by philipp-greenique** [comment]
I was trying to find a solution on my own but ended in a situation where i overrode a method to prevent the adjustment of the stock but i kept going.
The "Disable Reservation" module it self works but in some instances it seems there are still some bugs.
We went at the end the extra mile by disabling all of the new inventory modules, and revert all of our fixes toward these modules.
https://magento.stackexchange.com/a/283381/85845

**Comment by convenient** [comment]
@philipp-greenique If you have any of the attempted code to share it may be useful for others working on this in future :) 

Yes, disabling MSI entirely is also an option.

**Comment by philipp-greenique** [comment]
@convenient 
We tried to disable the execute() method of
Magento\InventorySales\Model\ReturnProcessor\ProcessRefundItems
but it seemed that was not the right one, the stock kept changing.
I'm sorry but this is all, hope one will find a solid solution. fingers are crossed :)

**Comment by seansan** [comment]
Be careful .. MSI is here to stay. We need to find ways to accept it, then
refine / improve it.

**Comment by tuyennn** [comment]
Same problem, anyone got an idea for this issue?

**Comment by gianstraf** [comment]
Hi, we have found this possible solution

**Comment by TechOS-PL** [comment]
M2.4.4

1.
Magento\InventorySales\Model\ReturnProcessor\GetInvoicedItemsPerSourceByPriority 
remove `&& $orderItem->getIsVirtual()` on line 185
**private function isValidItem** should look like this:
`private function isValidItem(OrderItemModel $orderItem, array $returnToStockItems): bool
    {
        return (in_array($orderItem->getId(), $returnToStockItems)
                || in_array($orderItem->getParentItemId(), $returnToStockItems))
                && !$orderItem->isDummy();
    }`

2.
Magento\InventorySales\Plugin\Sales\OrderManagement\DeductSourceItemQuantityOnRefundPlugin
change `&& !$item->getBackToStock();` to `&& $item->getBackToStock();`
**private function isValidItem** should look like this:
`private function isValidItem(string $sku, CreditmemoItem $item): bool
    {
        /** @var OrderItemInterface $orderItem */
        $orderItem = $item->getOrderItem();
        // Since simple products which are the part of a grouped product are saved in the database
        // (table sales_order_item) with product type grouped, we manually change the type of
        // product from grouped to simple which support source management.
        $typeId = $orderItem->getProductType() === 'grouped' ? 'simple' : $orderItem->getProductType();

        $productType = $typeId ?: $this->getProductTypesBySkus->execute(
            [$sku]
        )[$sku];

        return $this->isSourceItemManagementAllowedForProductType->execute($productType)
                && $item->getQty() > 0
                && !$item->getBackToStock();
    }`
