### ISSUE TITLE
Error on success page in Magento 2.4.2-p1

### ISSUE THREAD

**Issue by andresa80** [AmpersandHQ/magento2-disable-stock-reservation#87]
Hi, i have installed ampersand module without problems, but when i try to place an order the success page does not appear.
The order is in backed and i receive its confirmation email with correct data.
Instead of the success page, a blank page appears indicating the exception. Other issue, in backend i cannot view order page, for the same error on the success page.
This is the error. What could it be? Thanks

main.CRITICAL: Error: Call to undefined method Magento\Sales\Api\Data\OrderExtension::setSources() in /var/www/appuser0/mysite.it/202210240916/app/code/Ampersand/DisableStockReservation/Plugin/Model/OrderRepositoryPlugin.php:135
Stack trace:
#0 /var/www/appuser0/mysite.it/202210240916/app/code/Ampersand/DisableStockReservation/Plugin/Model/OrderRepositoryPlugin.php(85): Ampersand\DisableStockReservation\Plugin\Model\OrderRepositoryPlugin->applyExtensionAttributesToOrder(Object(Trustedshops\Trustedshops\Model\Rewrite\Sales\Order\Interceptor), Array)
#1 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(146): Ampersand\DisableStockReservation\Plugin\Model\OrderRepositoryPlugin->afterGet(Object(Magento\Sales\Model\OrderRepository\Interceptor), Object(Trustedshops\Trustedshops\Model\Rewrite\Sales\Order\Interceptor), 335)
#2 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}(335)
#3 /var/www/appuser0/mysite.it/202210240916/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(23): Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins('get', Array, Array)
#4 /var/www/appuser0/mysite.it/202210240916/vendor/magento/module-inventory-in-store-pickup-sales/Model/IsStorePickupOrder.php(47): Magento\Sales\Model\OrderRepository\Interceptor->get(335)
#5 /var/www/appuser0/mysite.it/202210240916/vendor/magento/module-inventory-in-store-pickup-frontend/Block/Checkout/Onepage/Success/IsOrderStorePickup.php(47): Magento\InventoryInStorePickupSales\Model\IsStorePickupOrder->execute(335)
#6 /var/www/appuser0/mysite.it/202210240916/vendor/magento/module-inventory-in-store-pickup-frontend/view/frontend/templates/success.phtml(15): Magento\InventoryInStorePickupFrontend\Block\Checkout\Onepage\Success\IsOrderStorePickup->execute()
#7 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/appuse...')
#8 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Onepage\Success\Interceptor), '/var/www/appuse...', Array)
#9 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#10 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Checkout\Block\Onepage\Success\Interceptor), '/var/www/appuse...', Array)
#11 /var/www/appuser0/mysite.it/202210240916/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, Array)
#12 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Magento\Checkout\Block\Onepage\Success\Interceptor), '/var/www/appuse...', Array)
#13 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/var/www/appuse...')
#14 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml()
#15 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#16 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#17 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#18 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Block\Onepage\Success\Interceptor->___callParent('toHtml', Array)
#19 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Block\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}()
#20 /var/www/appuser0/mysite.it/202210240916/generated/code/Magento/Checkout/Block/Onepage/Success/Interceptor.php(23): Magento\Checkout\Block\Onepage\Success\Interceptor->___callPlugins('toHtml', Array, Array)
#21 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(578): Magento\Checkout\Block\Onepage\Success\Interceptor->toHtml()
#22 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('checkout.succes...')
#23 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('checkout.succes...')
#24 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('checkout.succes...', false)
#25 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('content', false)
#26 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('content')
#27 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('content', false)
#28 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main', false)
#29 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('main')
#30 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('main', false)
#31 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('columns', false)
#32 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#33 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('columns', false)
#34 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#35 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#36 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('main.content', false)
#37 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#38 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#39 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#40 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#41 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('root')
#42 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement('root')
#43 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#44 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#45 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#46 /var/www/appuser0/mysite.it/202210240916/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#47 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#48 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#49 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#50 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#51 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#52 /var/www/appuser0/mysite.it/202210240916/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#53 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#54 /var/www/appuser0/mysite.it/202210240916/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#55 /var/www/appuser0/mysite.it/202210240916/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#56 {main} [] []

**Comment by convenient** [comment]
hey @andresa80 I'm closing this as it's already being discussed on #75

We've not managed to reproduce it anywhere, to me it really feels like it may be some part of your deployment process perhaps holding some cached redis value

Some people said deploying twice fixed it, which leads credence to this idea but without knowing your deployment process end to end to reproduce I cannot really proceed further.
