### ISSUE TITLE
Qty not deducting after order placement in Magento 2.4.2

### ISSUE THREAD

**Issue by anjalykv** [AmpersandHQ/magento2-disable-stock-reservation#89]
Hi,

I have installed the extension in our Magento 2.4.2 and truncated the inventory reservation table. But the QTY not deduct after an order is placed. Cleared cache and re-index. But no change. Let us know how can I fix the issue.

**Comment by convenient** [comment]
Hello @anjalykv did marks recommendation fix your issue?

**Comment by convenient** [comment]
Closing due to lack of details.
