### ISSUE TITLE
Uninstall  Ampersand Stock Reservation plugin and restore QTY reservation

### ISSUE THREAD

**Issue by anjalykv** [AmpersandHQ/magento2-disable-stock-reservation#94]
Hi,

Let us know, how can we uninstall Ampersand Stock Reservation module and it's related changes. We have disabled the plugin but the stock reservation is not working as expected. When an order is made and shipped, the QTY and saleable QTY increased instead of decrease.  Please help us to restore the website back to it's default stage by uninstalling Ampersand plugin and it's related changes.

**Comment by convenient** [comment]
> We have disabled the plugin

Can you confirm how you have done this? Disabling this module and composer removing it should be enough

**Comment by convenient** [comment]
hello @anjalykv did you get this uninstalled?
